language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

services:
  - postgres

addons:
  postgresql: "9.3"

before_script:
  - psql -c 'create database test_lstr_yo_pdo;' -U postgres
  - cp tests/config/dist/config.travis.php tests/config/config.php

install:
  - composer install

after_script:
  - vendor/bin/test-reporter --coverage-report=tests/log/coverage.xml
